### ISSUE TITLE
polar schema doesn't work

### ISSUE THREAD

**Issue by coco-sha** [arufa-research/polar#103]
warning: `secretswap` (lib) generated 3 warnings
   Compiling secretswap-generator v2.1.0 (/home/ay/arufa-research/secretswap2.0/contracts/generator)
    Finished dev [unoptimized + debuginfo] target(s) in 15.43s
     Running `/home/ay/arufa-research/secretswap2.0/target/debug/examples/schema`
Created /home/ay/arufa-research/secretswap2.0/contracts/generator/schema/instantiate_msg.json
Created /home/ay/arufa-research/secretswap2.0/contracts/generator/schema/execute_msg.json
Created /home/ay/arufa-research/secretswap2.0/contracts/generator/schema/query_msg.json
Creating TS schema objects for contract in directory: artifacts/typescript_schema
Error: [info.items] case not handled by transpiler. contact maintainers.
    at getPropertyType (/home/ay/.config/yarn/global/node_modules/polar-wasm-ast-types/main/utils/types.js:134:15)
    at /home/ay/.config/yarn/global/node_modules/polar-wasm-ast-types/main/utils/types.js:236:7
    at Array.map (<anonymous>)
    at createTypedObjectParams (/home/ay/.config/yarn/global/node_modules/polar-wasm-ast-types/main/utils/types.js:186:26)
    at createPropertyFunctionWithObjectParams (/home/ay/.config/yarn/global/node_modules/polar-wasm-ast-types/main/wasm.js:131:49)
    at /home/ay/.config/yarn/global/node_modules/polar-wasm-ast-types/main/wasm.js:178:12
    at Array.map (<anonymous>)
    at Object.createQueryInterface (/home/ay/.config/yarn/global/node_modules/polar-wasm-ast-types/main/wasm.js:174:60)
    at generateTsSchema (/home/ay/.config/yarn/global/node_modules/secret-polar/dist/lib/compile/tsSchema.js:64:21)
    at generateSchema (/home/ay/.config/yarn/global/node_modules/secret-polar/dist/lib/compile/compile.js:102:5)
{
  type: 'object',
  required: [ 'lp_token' ],
  properties: {
    lp_token: { type: 'array', items: [Array], maxItems: 2, minItems: 2 }
  }
} lp_token
An unexpected error occurred: [info.items] case not handled by transpiler. contact maintainers.

**Comment by amityadav0** [comment]
#114
